version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: etl-postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: etl-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: etl-airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_pass@postgres:5432/etl_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username admin \
          --password admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: etl-airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      mongo:
        condition: service_started
    restart: always
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_pass@postgres:5432/etl_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: etl-airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      mongo:
        condition: service_started
    restart: always
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_pass@postgres:5432/etl_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts

volumes:
  postgres_data:
  mongo_data: